allowBuilds:
  '@parcel/watcher': true
  electron: true
  electron-winstaller: true
  esbuild: true
  extract-file-icon: false
  uiohook-napi: false
  vue-demi: true
  ym-fullscreen-detector: false
minimumReleaseAgeExclude:
  - ym-release@2.0.0
  - ym-fullscreen-detector@0.1.2
  - plugin-electron-ipc@0.1.2

